# z1015 Logik Part Driver

# Auto-generated by FPGA Architect

from logik.devices.logik_fpga import LogikFPGA

import os.path


####################################################
# Setup for z1015 FPGA
####################################################

class z1015(LogikFPGA):
    '''
    Logik driver for z1015
    '''

    def __init__(self):
        super().__init__()
        self.set_name('z1015')

        self.define_tool_parameter('convert_bitstream', 'bitstream_map', 'file',
                                   'bitstream map')
        self.set_dataroot("logik-fpga-z1015", os.path.dirname(__file__))

        self.package.set_vendor("fpga_architect")

        self.set_vpr_devicecode("z1015")

        self.set_lutsize(4)
        yosys_featureset = []
        yosys_featureset.append("async_reset")
        yosys_featureset.append("async_set")
        yosys_featureset.append("enable")

        self.add_yosys_featureset(yosys_featureset)
        self.set_vpr_clockmodel("route")

        with self.active_dataroot("logik-fpga-z1015"):
            self.set_vpr_archfile('z1015.xml')
            self.set_vpr_graphfile('z1015_rr_graph.xml')
            self.set_yosys_config('z1015_yosys_config.json')
            self.set_yosys_flipfloptechmap('tech_flops.v')
            self.set_yosys_memorymap(techmap='tech_bram.v')
            self.set_yosys_memorymap(libmap='bram_memory_map.txt')
            self.set_yosys_dsptechmap('tech_dsp.v', options=['DSP_SIGNEDONLY=1', 'DSP_A_MAXWIDTH=18', 'DSP_B_MAXWIDTH=18', 'DSP_A_MINWIDTH=2', 'DSP_B_MINWIDTH=2', 'DSP_Y_MINWIDTH=2', 'DSP_NAME=_dsp_block_'])
            self.add_yosys_macrolib('tech_dsp_blackbox.v')

        # Define the macros that can be techmapped to based on the modes
        # that exist in the design
        self.add_yosys_registertype(['dff', 'dffe', 'dffeh', 'dffehl', 'dffehlr', 'dffehlrs', 'dffehls', 'dffehr', 'dffehrs', 'dffehs', 'dffel', 'dffelr', 'dffelrs', 'dffels', 'dffer', 'dffers', 'dffes', 'dffh', 'dffhl', 'dffhlr', 'dffhlrs', 'dffhls', 'dffhr', 'dffhrs', 'dffhs', 'dffl', 'dfflr', 'dfflrs', 'dffls', 'dffr', 'dffrs', 'dffs'])
        self.add_vpr_registertype(['dff', 'dffe', 'dffeh', 'dffehl', 'dffehlr', 'dffehlrs', 'dffehls', 'dffehr', 'dffehrs', 'dffehs', 'dffel', 'dffelr', 'dffelrs', 'dffels', 'dffer', 'dffers', 'dffes', 'dffh', 'dffhl', 'dffhlr', 'dffhlrs', 'dffhls', 'dffhr', 'dffhrs', 'dffhs', 'dffl', 'dfflr', 'dfflrs', 'dffls', 'dffr', 'dffrs', 'dffs'])

        self.add_yosys_dsptype(['dsp_mult', 'efpga_acc', 'efpga_acc_regi', 'efpga_adder', 'efpga_adder_regi', 'efpga_adder_regio', 'efpga_adder_rego', 'efpga_macc', 'efpga_macc_pipe', 'efpga_macc_pipe_regi', 'efpga_macc_regi', 'efpga_mult', 'efpga_mult_addc', 'efpga_mult_addc_regi', 'efpga_mult_addc_regio', 'efpga_mult_addc_rego', 'efpga_mult_regi', 'efpga_mult_regio', 'efpga_mult_rego'])
        self.add_vpr_dsptype(['dsp_mult', 'efpga_acc', 'efpga_acc_regi', 'efpga_adder', 'efpga_adder_regi', 'efpga_adder_regio', 'efpga_adder_rego', 'efpga_macc', 'efpga_macc_pipe', 'efpga_macc_pipe_regi', 'efpga_macc_regi', 'efpga_mult', 'efpga_mult_addc', 'efpga_mult_addc_regi', 'efpga_mult_addc_regio', 'efpga_mult_addc_rego', 'efpga_mult_regi', 'efpga_mult_regio', 'efpga_mult_rego'])

        self.add_yosys_bramtype(['sdpram_1024x16', 'sdpram_16384x1', 'sdpram_2048x8', 'sdpram_4096x4', 'sdpram_8192x2', 'spram_1024x16', 'spram_16384x1', 'spram_2048x8', 'spram_4096x4', 'spram_512x32', 'spram_8192x2', 'sram_sdp', 'sram_sp', 'sram_tdp', 'tdpram_1024x16', 'tdpram_16384x1', 'tdpram_2048x8', 'tdpram_4096x4', 'tdpram_8192x2'])
        self.add_vpr_bramtype(['sdpram_1024x16', 'sdpram_16384x1', 'sdpram_2048x8', 'sdpram_4096x4', 'sdpram_8192x2', 'spram_1024x16', 'spram_16384x1', 'spram_2048x8', 'spram_4096x4', 'spram_512x32', 'spram_8192x2', 'sram_sdp', 'sram_sp', 'sram_tdp', 'tdpram_1024x16', 'tdpram_16384x1', 'tdpram_2048x8', 'tdpram_4096x4', 'tdpram_8192x2'])

        # TODO: blackbox_options

        with self.active_dataroot("logik-fpga-z1015"):
            self.set_convert_bitstream_bitstream_map('z1015_bitstream_map.json')
            self.set_vpr_constraintsmap('z1015_constraint_map.json')

        self.set_vpr_channelwidth(150)

        with self.active_dataroot("logik-fpga-z1015"):
            with self.active_fileset("z1015_opensta_liberty_files"):
                self.add_file('vtr_primitives.lib')
                self.add_file(['tech_flops.lib', 'tech_dsp.lib', 'tech_bram.lib'])
                self.add_opensta_liberty_fileset()

        self.set_vpr_router_lookahead('classic')


#########################
if __name__ == "__main__":
    fpga = z1015
    assert fpga.check_filepaths()
    fpga.write_manifest(f'{fpga.design}.json')
