name: Wheels

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Wheels
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hynek/build-and-inspect-python-package@v2

  publish:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.12.4

      - name: Add wheels to GitHub release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
